page1 = action_wheel:newPage()
action_wheel:setPage(page1)
page1:newAction(1):item("diamond_sword"):title("Swordfighter")
    :onLeftClick(function()
         models.models.main.Body.BodySword:setVisible(true)
         models.models.main.LeftArm.LeftASword:setVisible(true)
         models.models.main.RightArm.RightASword:setVisible(true)
         models.models.main.Body.BodyZephyr:setVisible(false)
         models.models.main.LeftArm.LeftAZephyr:setVisible(false)
         models.models.main.RightArm.RightAZephyr:setVisible(false)
    end)
page1:newAction(2):item("cod"):title("Zephyr")
    :onLeftClick(function ()
        models.models.main.Body.BodySword:setVisible(false)
        models.models.main.LeftArm.LeftASword:setVisible(false)
        models.models.main.RightArm.RightASword:setVisible(false)
        models.models.main.Body.BodyZephyr:setVisible(true)
        models.models.main.LeftArm.LeftAZephyr:setVisible(true)
        models.models.main.RightArm.RightAZephyr:setVisible(true)
    end)
page1:newAction(3):title("None")
    :onLeftClick(function ()
        models.models.main.Body.BodySword:setVisible(false)
        models.models.main.LeftArm.LeftASword:setVisible(false)
        models.models.main.RightArm.RightASword:setVisible(false)
        models.models.main.Body.BodyZephyr:setVisible(false)
        models.models.main.LeftArm.LeftAZephyr:setVisible(false)
        models.models.main.RightArm.RightAZephyr:setVisible(false)
    end)    



